name: Android CI

on:
  push:
    branches: [ ftx1 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Execute skyline dispatch event
      if: contains(github.ref, 'ftx1')
      env:
        GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
      run: |
        gh api repos/8bitDream/skyline/dispatches --raw-field event_type=ftx1